#
# Copyright (c) 2006-2024 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - https://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
# BeEF Configuration file

beef:
    version: '0.5.4.0'
    # More verbose messages (server-side)
    debug: false
    # More verbose messages (client-side)
    client_debug: false
    # Used for generating secure tokens
    crypto_default_value_length: 80

    # Credentials to authenticate in BeEF.
    # Used by both the RESTful API and the Admin interface
    credentials:
        user:   "beef"  # You can change these to your custom username and password
        passwd: "beef"  # You can change these to your custom password

    # Interface / IP restrictions
    restrictions:
        # subnet of IP addresses that can hook to the framework
        permitted_hooking_subnet: ["0.0.0.0/0", "::/0"]
        # subnet of IP addresses that can connect to the admin UI
        permitted_ui_subnet: ["0.0.0.0/0", "::/0"]
        # subnet of IP addresses that cannot be hooked by the framework
        excluded_hooking_subnet: []
        # slow API calls to 1 every api_attempt_delay seconds
        api_attempt_delay: "0.05"

    # HTTP server
    http:
        debug: false # Puma::Logging.debug, very verbose. Prints also full exception stack trace.
        host: "0.0.0.0"  # Listen on all IPs
        port: "3000"  # Render uses port 3000 for web services

        # Decrease this setting to 1,000 (ms) for more responsiveness
        xhr_poll_timeout: 1000

        # Public Domain / Reverse Proxy / Port Forwarding
        #
        # In order for the client-side BeEF JavaScript hook to be able to connect to BeEF,
        # the hook JavaScript needs to be generated with the correct connect-back details.
        #
        # If you're using a public domain name, reverse proxy, or port forwarding you must
        # configure the public-facing connection details here.

        # public:
        #     host: "beef.local" # public hostname/IP address
        #     port: "443" # public port (443 if the public server is using HTTPS)
        #     https: false # true/false

        # If using any reverse proxy you should also set allow_reverse_proxy to true below.
        # Note that this causes the BeEF server to trust the X-Forwarded-For HTTP header.
        allow_reverse_proxy: true  # Enable for reverse proxy use

        # Hook
        hook_file: "/hook.js"
        hook_session_name: "BEEFHOOK"

        # Allow one or multiple origins to access the RESTful API using CORS
        restful_api:
            allow_cors: false
            cors_allowed_domains: "http://browserhacker.com"

        # Prefer WebSockets over XHR-polling when possible.
        websocket:
            enable: true  # Enable WebSockets
            port: 61985  # WebSocket port
            secure: true  # Use secure WebSockets (WSS)
            secure_port: 61986  # Secure WebSocket port
            ws_poll_timeout: 5000  # Poll timeout for WebSocket connections
            ws_connect_timeout: 500  # Timeout for establishing WebSocket connection

        # Imitate a specified web server (default root page, 404 default error page, 'Server' HTTP response header)
        web_server_imitation:
            enable: true
            type: "apache"  # Supported: apache, iis, nginx
            hook_404: false  # Inject BeEF hook in HTTP 404 responses
            hook_root: false  # Inject BeEF hook in the server home page

        # Experimental HTTPS support for the hook / admin / all other Puma managed web services
        https:
            enable: false  # Render provides HTTPS automatically, so this can remain false
            key: "beef_key.pem"
            cert: "beef_cert.pem"

    database:
        file: "beef.db"

    # Autorun Rule Engine
    autorun:
        result_poll_interval: 300
        result_poll_timeout: 5000
        continue_after_timeout: true

    # Enables DNS lookups on zombie IP addresses
    dns_hostname_lookup: false

    # IP Geolocation
    geoip:
        enable: true
        database: '/usr/share/GeoIP/GeoLite2-City.mmdb'

    # Extension configurations
    extension:
        admin_ui:
            enable: true
            base_path: "/ui"
        demos:
            enable: true
        events:
            enable: true
        evasion:
            enable: false
        requester:
            enable: true
        proxy:
            enable: true
        network:
            enable: true
        metasploit:
            enable: false
        social_engineering:
            enable: false
        xssrays:
            enable: true
